import streamlit as st
import random
import time
import re
import torch
from transformers import pipeline

# ---------------------------------------------------
# 1. 載入 Hugging Face 模型（用 cache，避免每次重載）
# ---------------------------------------------------
@st.cache_resource
def load_detector():
    """
    載入 AI 文字偵測模型（Hugging Face）。
    這裡示範使用 fakespot-ai/roberta-base-ai-text-detection-v1。
    """
    device = 0 if torch.cuda.is_available() else -1
    clf = pipeline(
        "text-classification",
        model="fakespot-ai/roberta-base-ai-text-detection-v1",
        device=device
    )
    return clf

def clean_text(text: str) -> str:
    """簡單文字清理：去除多餘空白與換行。"""
    text = text.replace("\u200b", " ")
    text = text.replace("\n", " ")
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def main():
    """
    Main function to run the AI Content Detector Streamlit app.
    """
    st.set_page_config(page_title="AI Content Detector", page_icon="🤖")

    st.title("AI Content Detector")
    st.write(
        "This tool estimates whether your text is more likely "
        "written by a human or generated by AI."
    )
    st.caption("⚠ This is a probability estimate, not definitive proof.")

    # Initialize session state
    if 'text_content' not in st.session_state:
        st.session_state.text_content = ""

    sample_texts = [
        "There is no relation at all between Fortier and Profiler but the fact that both are police series about violent crimes. Profiler looks crispy, Fortier looks classic. Profiler plots are quite simple. Fortier's plot are far more complicated... Fortier looks more like Prime Suspect, if we have to spot similarities... The main character is weak and weirdo, but have \"clairvoyance\". People like to compare, to judge, to evaluate. How about just enjoying? Funny thing too, people writing Fortier looks American but, on the other hand, arguing they prefer American series (!!!). Maybe it's the language, or the spirit, but I think this series is more English than American. By the way, the actors are really good and funny. The acting is not superficial at all...",
        "This movie is a great. The plot is very true to the book which is a classic written by Mark Twain. The movie starts of with a scene where Hank sings a song with a bunch of kids called \"when you stub your toe on the moon\" It reminds me of Sinatra's song High Hopes, it is fun and inspirational. The Music is great throughout and my favorite song is sung by the King, Hank (bing Crosby) and Sir \"Saggy\" Sagamore. OVerall a great family movie or even a great Date movie. This is a movie you can watch over and over again. The princess played by Rhonda Fleming is gorgeous. I love this movie!! If you liked Danny Kaye in the Court Jester then you will definitely like this movie.",
        "George P. Cosmatos' \"Rambo: First Blood Part II\" is pure wish-fulfillment. The United States clearly didn't win the war in Vietnam. They caused damage to this country beyond the imaginable and this movie continues the fairy story of the oh-so innocent soldiers. The only bad guys were the leaders of the nation, who made this war happen. The character of Rambo is perfect to notice this. He is extremely patriotic, bemoans that US-Americans didn't appreciate and celebrate the achievements of the single soldier, but has nothing but distrust for leading officers and politicians. Like every film that defends the war (e.g. \"We Were Soldiers\") also this one avoids the need to give a comprehensible reason for the engagement in South Asia. And for that matter also the reason for every single US-American soldier that was there. Instead, Rambo gets to take revenge for the wounds of a whole nation. It would have been better to work on how to deal with the memories, rather than suppressing them. \"Do we get to win this time?\" Yes, you do.",
        "In the process of trying to establish the audiences' empathy with Jake Roedel (Tobey Maguire) the filmmakers slander the North and the Jayhawkers. Missouri never withdrew from the Union and the Union Army was not an invading force. The Southerners fought for State's Rights: the right to own slaves, elect crooked legislatures and judges, and employ a political spoils system. There's nothing noble in that. The Missourians could have easily traveled east and joined the Confederate Army. It seems to me that the story has nothing to do with ambiguity. When Jake leaves the Bushwhackers, it's not because he saw error in his way, he certainly doesn't give himself over to the virtue of the cause of abolition.",

        "While this movie's style isn't as understated and realistic as a sound version probably would have been, this is still a very good film. In fact, it was seen as an excellent film in its day, as it was nominated for the first Best Picture Oscar (losing to WINGS). I still consider WINGS to be a superior film, but this one is excellent despite a little bit of overacting by the lead, Emil Jannings. Jannings is a general from Czarist Russia who is living out his final days making a few bucks in the 1920s by being a Hollywood extra. His luck appears to have changed as he gets a casting call--to play an Imperial Russian general fighting against the Communists during the revolution. Naturally this isn't much of a stretch acting-wise, but it also gets the old man to thinking about the old days and the revolution. Exactly what happens next I'll leave to you, but it's a pretty good film--particularly at the end. By the way, look for William Powell as the Russian director. Despite being made in 1928, with the makeup he doesn't look much younger than he did in many of his later films.",
        "I give this movie 7 out of 10 because the villains were interesting in their roles and the unknown batwoman creates an interesting \"guess who\" game. The movie, however, needs more Robin in it. He appeared in the movie in the beginning and sporadically throughout the rest. I always thought the new animated series did little justice to the neat new Robin character, let alone Knightwing. This movie just continues that bad tradition. The movie spends too much time on Bruce Wayne and his romance which wouldn't be so bad in one movie if the romance wasn't so unbelievable. It is still a good movie if you are a Batman fan and I would recommend watching it.",
        "really awful... lead actor did OK... the film, plot etc was completely crap and inaccurate it may as well have been a sequel to well... anything it had little or no relevance to Carlitos Way... and should be avoided like the plague by any Carlito's ways fans... no mention of Gail in fact he ends up with some other bird, no mention of Klienfelt, no mention of how he got caught, no mention of how he ended up in jail... they attempted to make it like the original with flash backs at the beginning... but to be honest when rating it I was looking for a zero mark... unfortunately I had to rate it higher... Its a terrible attempt to cash in on what was one of the best films of the 90's... overall it was approximately 6 and 2 hours of my life waste d... for all the \"action\" in it, it was truly boring slow and predictable... again to any Carltio's Way fans avoid this fiasco...",
        "Good grief I can't even begin to describe how poor this film is. Don't get me wrong, I wasn't expecting much to begin with. Let's face it, a PG-13 slasher flick is pre-destined to be missing the ummm... slashing, so no one should be surprised by the lack of gore. But it was the level of incompetence and clich on display in all the other aspects of this movie is what really blew me away. We have a protagonist who is quite simply so completely useless that you find yourself rooting for the bad guy. And here's a turnup for the books... SHE NEVER CHANGES - hence breaking the cardinal rule of basic screen writing - character development. If you think by the end of this film the poor little girl is going to turn around and finally kick some arse then think again. On top of this, we're handed possibly the least intriguing (and definitely the least scary) killer ever to grace the genre. I'm not joking when I say that Dora the Explorer has scarier villains than this movie. Finally, because all the potential for tension or gratuity is removed by the inept (and apparently thirteen-year-old) director, what could possibly be left to fill up 2 hours of screen time? Closets, that's what. Lots and lots of closets: big closets, small closets, mirrored closets, closets to Narnia, so many damned closets you'll not want to dress yourself for another year. In fact this movie should have just been called \"CLOSET\", and had a picture of a big scary coathanger on the DVD case. On the back it could have had a photograph of the audience falling asleep and a quote by Roger and Ebert - something to the extent of: \"what the f*@! did we just waste our time watching!\"",
        "Home Room deals with a Columbine-like high-school shooting but rather than hashing over the occurrence itself the film portrays the aftermath and what happened to the survivors, their trauma, guilt and denial. *Spoilers* The shooting itself is treated as a foregone conclusion, with no action footage other than the reaction of an almost teenage SWAT commando after shooting the high school killer. The film has three protagonists; a detective investigating the crime of which no guilty parties are left to convict and two teenage girls surviving the incident, played by a very young Erika Christensen and Busy Philipps. The two girls having nothing in common besides the shooting are put together because of it and the drama ensues. Erika Christensen, though only 24 has been around the block so much that film viewers are pretty much acquainted with her solid and reliable style of acting. Busy Philipps, three years older than Christensen and altogether unknown to me, blew me away with her overwhelming dramatic strength and screen presence. This girl was the part. It's a great movie and it connects to you with its intimate focus on the fragile yet growing relationship between the two traumatized girls. Gus van Sant's Elephant (2003) though good, seems almost superficial and paltry compared to Home Room when it comes to dramatic flair and acting. What I can see this film got very little screen time and exposure - so much more a loss for an equally traumatized America. Ten out of Ten",
        "While those graduating on time may have significantly more options, those who graduate early may face the challenge of having to prove the depth of their knowledge and skills despite having a shorter-term education. It is crucial to consider all angles when considering graduating early and ensure that informed decisions are made.. Finally, it is important to take into account how graduating early can affect a student's opportunities in the future. First and foremost, a student's individual academic requirements must be taken into consideration since obtaining credits to graduate on time is a priority. Furthermore, graduating early can have a positive effect on building a student's self-confidence, but it is important to remember that elective courses are often invaluable due to the breadth of knowledge and experiences they provide.",
        "As high school students consider graduating early by taking advantage of a program that offers them the opportunity to complete their studies in three years instead of four, it is important to consider the potential upsides and downsides",
        "Summer break is an important time for many students and families, as it allows an opportunity for rest and relaxation after a long year of work and school. One of the pros of summer break is that both students and teachers are able to reduce their stress levels by having an extended period of time off from their studies or jobs. During this time, families can also reconnect and bond together more closely as they have an extended period of time to spend at home, away from the pressures of day-to-day life. Additionally, students have the option of taking courses over the summer period in order to graduate earlier than planned. They also have access to a virtually unlimited range of resources that wouldn't necessarily be available to them in a traditional classroom setting.",
        "Additionally, distance learning is widely accessible, removing all physical barriers to education. By allowing students to access courses anywhere with an internet connection and receive the same educational content, distance learning has proven to be a more preferable option for those seeking an alternative to traditional learning.. By comparison, traditional in-class learning is done within a confined physical environment, limiting both student accessibility and teaching capabilities. This means they can listen to lectures, submit assignments, and take exams in their own free time. Whether it's due to geographical distance or other circumstances, distance learning can provide students with options they wouldn't have in traditional settings. Therefore, distance learning can provide a number of advantages that make it a more preferable option for learners.",
        "For instance, distance learning can generally be more flexible than traditional learning. For example, students who have disabilities or chronic illnesses can benefit from distance learning, as they can interact with the same educational content from the comfort of their own home.",
        "Overall, it is clear that distance learning can provide a range of benefits over traditional in-class learning. Students have the option to access course material 24/7, allowing them to work around their own personal schedules.",
        "Distance learning has become increasingly more popular in recent years, as technology has allowed us to create innovative learning experiences that can be accessed from almost anywhere in the world",
        "On the one hand, setting a 10PM Weekday and Midnight curfew for teenagers instills a sense of responsibility and safety.",
        "On the other hand, setting such a restriction on teenagers could appear to be an attempt to prevent them from exploring the world and engaging in age-appropriate activities and instead keeps them at home in a supervised environment. Moreover, it could teach young people that their parents don't fully trust them to make the right decisions and that they should not be expected to be in control of their own lives. It sends the message that young people should be careful about the choices they make and that staying out too late can put them at risk. It is important to consider both sides of the argument and to choose the best course of action that works for each individual family.. Furthermore, it can provide structure and ensure that teens are completing their educational and extracurricular activities, and getting enough sleep to remain healthy and alert for the next day.",
        "When it comes to setting curfews for teenagers, it is a difficult and oftentimes divisive decision between parents, children and society.",
        "Overall, whether or not to set a 10PM Weekday and Midnight curfew for teenagers is an issue that must be weighed carefully",
        "The study included 200 students from multiple high schools across the country and monitored their responses to praise and criticism. This provides evidence that praising student's deficient work can have a positive effect on their development. The findings showed that students who were praised for work that was below expectations had better self-esteem, higher academic standards, and were more likely to graduate high school than those who received criticism. It follows then that providing appropriate praise which encourages and motivates students should be incorporated into educational curriculums.. A recent study investigated how praising student's deficient work affects their self-esteem, learning standards, and their likelihood of graduating high school.",
        "As the pressure to succeed increases, the role of praise in educational settings has become more prominent",
        "Having a positive attitude is one of the most beneficial things a person can do to foster success and growth in life. Not only this, but treating animals with care and kindness can also help a person realize successes and happiness in life. This can create a strong support system for one's growth in life. To further this success, it is important to spend time with positive people who are motivated and understanding. A positive attitude can help build upon success because it allows for setting achievable goals, encourages healthy communication, and creates an optimistic outlook on life's challenges. Examples of how a positive attitude can help lead to success are seen in the workplace, in relationships, and in everyday life. Furthermore, it is important to show respect and responsibility to others in order to achieve success. All these elements are valuable in contributing to successful and positive life.",
        "Many online courses allow students to interact and discuss topics with their peers via video chat or instant messaging services, and this can lead to a more engaged learning experience.",
        "Taking classes from home has become more popular in recent years due to many benefits. For starters, students taking online classes can work around their own schedule. Since students don't have to pay for transportation, or for food at cafeterias, they can save money on the overall cost of the class.",
        "Parents can also be more trusting of their children taking classes from home since they don't have to leave their house and their attendance is monitored. Another benefit is the cost savings associated with online courses. Furthermore, not having an in-person instructor means that students can't be absent from class, which has a positive effect on their overall course grades.",
        "Finally, if any issue does arise with an online class, more often than not there is a helpdesk or online resource available to provide support and answers to any questions. This allows for flexibility to attend classes, do homework, and participate in activities without having to leave their home. As long as students are following course instructions, taking classes from home can be a great way for them to learn without having to leave the house.",
        "Most importantly, it can bring happiness not only to the individual but to the family as well. In order for this to happen, students must take full responsibility for their professional journey. If a student fails to meet their obligations, whether due to lack of knowledge or a simple lack of dedication, it can lead to severe repercussions.",
        "Overall, a professional career is on the utmost importance and comes with its own set of unique responsibilities. Students should also stay aware of the risks associated with neglecting their responsibilities. Students must remain fully aware of their personal goals and take ownership of their career in order to guarantee success and a happy future, both for themselves and their families. Only through diligence and hard work can a a student truly realize their full potential and reach their highest aspirations..",
        "Having a professional career is essential to living a successful and meaningful life. It is important that students pay close attention to what they're doing and take all the necessary steps to pursue their professional aspirations.",
        "However, it is not enough to merely pursue and secure a professional career. A professional career is one of the highest forms of responsibility and can come with a tremendous amount of pressure",
        "Since I was a child, I have expressed my creativity through the written word. Now I can create pieces that allow a wide range of people to look at a situation from a different perspective.. I value their feedback and opinion when it comes to my work and they have pushed me to improve by inspiring me to write in a way that encourages people to think critically.",
        "Overall, I am proud that I have used my passion to cultivate a unique skill over the years. I have had many amazing teachers who aided me in my journey. From reading classical works to understanding the importance of grammar, I have benefited greatly from their guidance. This has shaped my writing style and equipped me with the necessary tools to express my ideas accurately.",
        "Aside from my teachers, some of my closest friends also have influenced the way I write.",
        "One of my most remarkable talents I have developed over the years is my ability to write. I have always been an avid reader and my love for literature inspired me to explore the power of written expression.",
        "I have developed my writing skills mainly through practice and dedication. With the help of my teachers and. With the help of my teachers and friends, I have built upon the foundations of my writing abilities and refined my craft",
        "However, when weighing the pros and cons, it is important to take all factors into consideration and ensure that any potential policy changes are in the best interests of all involved..",
        "Extending school hours has become a controversial issue among educators, parents, and students alike. Lastly, it could give students an opportunity to interact more with teachers. With more time available, students could participate in councils and activities that promote problem-solving and teamwork. Supporters of this plan argue that it would offer students more quality time to focus on their studies, develop skills, and interact with their instructors. Secondly, extending school hours could offer students the opportunity to engage in extracurricular activities. Oftentimes, already tight student/family schedules could be disrupted due to the added time commitment. Spending more time with instructors outside of the classroom can help create a closer, more meaningful, student/teacher relationship.",
        "On the other hand, longer school hours could also result in stressful conditions for students. Longer school hours make it possible for teachers to spend more time exploring complex topics and for students to build deeper understanding of course material. However, there are also those who argue that extending school hours would put too much stress on students and disrupt their already tight schedules. Firstly, students would have more time to focus on their academics. Lastly, some argue that extended hours could extend to a loss of valuable sleep, resulting in poorer learning outcomes.",
        "In conclusion, there are some valid arguments both for and against extending school hours. In addition, spending more time in the classroom puts more strain on students who are already trying to balance school with other responsibilities such as sports teams, internships, and jobs.",
        "The pros of extending school hours are numerous"
    ]

    # Text area
    st.session_state.text_content = st.text_area(
        "Enter text to analyze",
        value=st.session_state.text_content,
        height=200
    )

    col1, col2 = st.columns(2)

    with col1:
        if st.button("Use Sample"):
            st.session_state.text_content = random.choice(sample_texts)
            st.rerun()

    with col2:
        if st.button("Check content"):
            if st.session_state.text_content.strip():
                with st.spinner("Analyzing with AI model..."):
                    # 載入模型
                    detector = load_detector()
                    # 清理文字
                    text = clean_text(st.session_state.text_content)
                    # 呼叫 Hugging Face 模型
                    result = detector(text)[0]  # {'label': 'AI' or 'Human', 'score': float}

                    raw_label = result["label"]
                    raw_score = float(result["score"])

                    # 將模型輸出轉成「AI 機率」
                    # 設計：若 label = AI → AI 機率 = score；Human → 1 - score
                    if raw_label.upper() == "AI":
                        ai_prob = raw_score
                    else:
                        ai_prob = 1.0 - raw_score

                    ai_prob = max(0.0, min(1.0, ai_prob))
                    human_prob = 1.0 - ai_prob

                    human_score = human_prob * 100

                    time.sleep(0.5)  # 小延遲增加「分析感」

                st.subheader("Analysis Result")

                # Progress bar 顯示「Human Content %」
                st.write(f"**{human_score:.1f}% Human Content**")
                st.progress(human_prob)

                # 文案邏輯保持接近你原本的
                if human_score > 80:
                    st.success("This text is likely written by a human.")
                elif human_score > 60:
                    st.warning("This text may contain some AI-generated content.")
                else:
                    st.error("This text is likely AI-generated.")



            else:
                st.warning("Please enter some text to analyze.")

if __name__ == "__main__":
    main()