import streamlit as st
import random
import time
import re
import torch
from transformers import pipeline

# ---------------------------------------------------
# 1. 載入 Hugging Face 模型（用 cache，避免每次重載）
# ---------------------------------------------------
@st.cache_resource
def load_detector():
    """
    載入 AI 文字偵測模型（Hugging Face）。
    這裡示範使用 fakespot-ai/roberta-base-ai-text-detection-v1。
    """
    device = 0 if torch.cuda.is_available() else -1
    clf = pipeline(
        "text-classification",
        model="fakespot-ai/roberta-base-ai-text-detection-v1",
        device=device
    )
    return clf

def clean_text(text: str) -> str:
    """簡單文字清理：去除多餘空白與換行。"""
    text = text.replace("\u200b", " ")
    text = text.replace("\n", " ")
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def main():
    """
    Main function to run the AI Content Detector Streamlit app.
    """
    st.set_page_config(page_title="AI Content Detector", page_icon="🤖")

    st.title("AI Content Detector")
    st.write(
        "This tool estimates whether your text is more likely "
        "written by a human or generated by AI."
    )
    st.caption("⚠ This is a probability estimate, not definitive proof.")

    # Initialize session state
    if 'text_content' not in st.session_state:
        st.session_state.text_content = ""

    sample_texts = [
        "The quick brown fox jumps over the lazy dog. This is a classic pangram often used for testing typefaces and keyboards. It contains every letter of the English alphabet.",
        "Artificial intelligence (AI) is intelligence demonstrated by machines, unlike the natural intelligence displayed by humans and animals. Leading AI textbooks define the field as the study of 'intelligent agents': any device that perceives its environment and takes actions that maximize its chance of successfully achieving its goals.",
        "The sun always shines brightest after the rain. Life is full of ups and downs, but it's important to remember that challenges are temporary and opportunities for growth are always present. Embrace change and keep moving forward.",
        "In a world where information is constantly flowing, critical thinking skills are more important than ever. Learning to evaluate sources, identify biases, and construct logical arguments are essential for navigating complex issues and making informed decisions.",
        "The history of the internet is a fascinating journey from a military research project to a global communication network. It has revolutionized how we work, learn, and interact with each other, constantly evolving with new technologies and applications."
    ]

    # Text area
    st.session_state.text_content = st.text_area(
        "Enter text to analyze",
        value=st.session_state.text_content,
        height=200
    )

    col1, col2 = st.columns(2)

    with col1:
        if st.button("Use Sample"):
            st.session_state.text_content = random.choice(sample_texts)
            st.rerun()

    with col2:
        if st.button("Check content"):
            if st.session_state.text_content.strip():
                with st.spinner("Analyzing with AI model..."):
                    # 載入模型
                    detector = load_detector()
                    # 清理文字
                    text = clean_text(st.session_state.text_content)
                    # 呼叫 Hugging Face 模型
                    result = detector(text)[0]  # {'label': 'AI' or 'Human', 'score': float}

                    raw_label = result["label"]
                    raw_score = float(result["score"])

                    # 將模型輸出轉成「AI 機率」
                    # 設計：若 label = AI → AI 機率 = score；Human → 1 - score
                    if raw_label.upper() == "AI":
                        ai_prob = raw_score
                    else:
                        ai_prob = 1.0 - raw_score

                    ai_prob = max(0.0, min(1.0, ai_prob))
                    human_prob = 1.0 - ai_prob

                    human_score = human_prob * 100

                    time.sleep(0.5)  # 小延遲增加「分析感」

                st.subheader("Analysis Result")

                # Progress bar 顯示「Human Content %」
                st.write(f"**{human_score:.1f}% Human Content**")
                st.progress(human_prob)

                # 文案邏輯保持接近你原本的
                if human_score > 80:
                    st.success("This text is likely written by a human.")
                elif human_score > 60:
                    st.warning("This text may contain some AI-generated content.")
                else:
                    st.error("This text is likely AI-generated.")

                # 額外顯示模型原始輸出（給你 debug / 寫論文）
                with st.expander("Model raw output"):
                    st.json(result)

            else:
                st.warning("Please enter some text to analyze.")

if __name__ == "__main__":
    main()